# Generated by Django 3.2.2 on 2021-06-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maqola', '0002_remove_article_kurish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
