# Generated by Django 3.2.2 on 2021-06-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maqola', '0004_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
